---

api_posts:
    type: rest
    resource: 'api/posts.yaml'
    prefix: /posts
    options:
        expose: true

api_tweets:
    type: rest
    resource: 'api/tweets.yaml'
    prefix: /tweets
    options:
        expose: true

api_users:
    type: rest
    resource: 'api/users.yaml'
    prefix: /users
    options:
        expose: true

api_login:
    path: /login
    controller: App\Controller\Api\SecurityController::postLogin
    defaults:
        _format: ~
    methods: [POST]

api_register:
    path: /register
    controller: App\Controller\Api\SecurityController::postRegister
    defaults:
        _format: ~
    methods: [POST]

tokens:
    path: /tokens/new
    controller: App\Controller\Api\TokensController::postNew
    defaults:
        _format: ~
    methods: [POST]
